config/routes.rb
DemoPrjct::Application.routes.draw do
  resources :carpools

  resources :microposts

  resources :custs

  resources :customers

  resources :users

end

app/models/cust.rb
class Cust < ActiveRecord::Base
  attr_accessible :address, :email, :name
end

app/controllers/custs_controller.rb
class CustsController < ApplicationController
  # GET /custs
  # GET /custs.json
  def index
    @custs = Cust.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @custs }
    end
  end

  # GET /custs/1
  # GET /custs/1.json
  def show
    @cust = Cust.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cust }
    end
  end

  # GET /custs/new
  # GET /custs/new.json
  def new
    @cust = Cust.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cust }
    end
  end

  # GET /custs/1/edit
  def edit
    @cust = Cust.find(params[:id])
  end

  # POST /custs
  # POST /custs.json
  def create
    @cust = Cust.new(params[:cust])

    respond_to do |format|
      if @cust.save
        format.html { redirect_to @cust, notice: 'Cust was successfully created.' }
        format.json { render json: @cust, status: :created, location: @cust }
      else
        format.html { render action: "new" }
        format.json { render json: @cust.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /custs/1
  # PUT /custs/1.json
  def update
    @cust = Cust.find(params[:id])

    respond_to do |format|
      if @cust.update_attributes(params[:cust])
        format.html { redirect_to @cust, notice: 'Cust was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cust.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custs/1
  # DELETE /custs/1.json
  def destroy
    @cust = Cust.find(params[:id])
    @cust.destroy

    respond_to do |format|
      format.html { redirect_to custs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/custs_helper.rb
module CustsHelper
end

app/views/custs/_form.html.erb
<%= form_for(@cust) do |f| %>
  <% if @cust.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cust.errors.count, "error") %> prohibited this cust from being saved:</h2>

      <ul>
      <% @cust.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/custs/edit.html.erb
<h1>Editing cust</h1>

<%= render 'form' %>

<%= link_to 'Show', @cust %> |
<%= link_to 'Back', custs_path %>

app/views/custs/index.html.erb
<h1>Listing custs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @custs.each do |cust| %>
  <tr>
    <td><%= cust.name %></td>
    <td><%= cust.email %></td>
    <td><%= cust.address %></td>
    <td><%= link_to 'Show', cust %></td>
    <td><%= link_to 'Edit', edit_cust_path(cust) %></td>
    <td><%= link_to 'Destroy', cust, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cust', new_cust_path %>

app/views/custs/new.html.erb
<h1>New cust</h1>

<%= render 'form' %>

<%= link_to 'Back', custs_path %>

app/views/custs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @cust.name %>
</p>

<p>
  <b>Email:</b>
  <%= @cust.email %>
</p>

<p>
  <b>Address:</b>
  <%= @cust.address %>
</p>


<%= link_to 'Edit', edit_cust_path(@cust) %> |
<%= link_to 'Back', custs_path %>