config/routes.rb
DemoPrjct::Application.routes.draw do
  resources :carpools

  resources :microposts

  resources :custs

  resources :customers

  resources :users

end

app/models/carpool.rb
class Carpool < ActiveRecord::Base
  attr_accessible :from, :to, :user_id
end

app/controllers/carpools_controller.rb
class CarpoolsController < ApplicationController
  # GET /carpools
  # GET /carpools.json
  def index
    @carpools = Carpool.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carpools }
    end
  end

  # GET /carpools/1
  # GET /carpools/1.json
  def show
    @carpool = Carpool.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @carpool }
    end
  end

  # GET /carpools/new
  # GET /carpools/new.json
  def new
    @carpool = Carpool.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @carpool }
    end
  end

  # GET /carpools/1/edit
  def edit
    @carpool = Carpool.find(params[:id])
  end

  # POST /carpools
  # POST /carpools.json
  def create
    @carpool = Carpool.new(params[:carpool])

    respond_to do |format|
      if @carpool.save
        format.html { redirect_to @carpool, notice: 'Carpool was successfully created.' }
        format.json { render json: @carpool, status: :created, location: @carpool }
      else
        format.html { render action: "new" }
        format.json { render json: @carpool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carpools/1
  # PUT /carpools/1.json
  def update
    @carpool = Carpool.find(params[:id])

    respond_to do |format|
      if @carpool.update_attributes(params[:carpool])
        format.html { redirect_to @carpool, notice: 'Carpool was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @carpool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carpools/1
  # DELETE /carpools/1.json
  def destroy
    @carpool = Carpool.find(params[:id])
    @carpool.destroy

    respond_to do |format|
      format.html { redirect_to carpools_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carpools_helper.rb
module CarpoolsHelper
end

app/views/carpools/_form.html.erb
<%= form_for(@carpool) do |f| %>
  <% if @carpool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@carpool.errors.count, "error") %> prohibited this carpool from being saved:</h2>

      <ul>
      <% @carpool.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :to %><br />
    <%= f.text_field :to %>
  </div>
  <div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :from %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carpools/edit.html.erb
<h1>Editing carpool</h1>

<%= render 'form' %>

<%= link_to 'Show', @carpool %> |
<%= link_to 'Back', carpools_path %>

app/views/carpools/index.html.erb
<h1>Listing carpools</h1>

<table>
  <tr>
    <th>User</th>
    <th>To</th>
    <th>From</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carpools.each do |carpool| %>
  <tr>
    <td><%= carpool.user_id %></td>
    <td><%= carpool.to %></td>
    <td><%= carpool.from %></td>
    <td><%= link_to 'Show', carpool %></td>
    <td><%= link_to 'Edit', edit_carpool_path(carpool) %></td>
    <td><%= link_to 'Destroy', carpool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Carpool', new_carpool_path %>

app/views/carpools/new.html.erb
<h1>New carpool</h1>

<%= render 'form' %>

<%= link_to 'Back', carpools_path %>

app/views/carpools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @carpool.user_id %>
</p>

<p>
  <b>To:</b>
  <%= @carpool.to %>
</p>

<p>
  <b>From:</b>
  <%= @carpool.from %>
</p>


<%= link_to 'Edit', edit_carpool_path(@carpool) %> |
<%= link_to 'Back', carpools_path %>